### PR TITLE
Add Water as an output to Stock Fuel Cells.

### PR DESCRIPTION
**Pull request by boiler1**
This modifies the stock fuel cells to also output water.  It takes the input fuel and outputs that much water * an efficiency modifier.  I set the efficiency at 90% but I think it should be lower personally.  Going with what other things are set to in the mod I think it is appropriate to make the efficiency high.

Also it dumps excess water if there is no storage, this way it doesn't break the fuel cells on existing craft with no water storage.

### CODE REVIEW

**Comment by BobPalmer** [comment]
tbh I think 90% is a bit over the top - it makes it more efficient to just burn off fuel to make water instead of mining for it...

**Comment by boiler1** [comment]
Agree, Originally I had it set at 25% but I think 50% sounds about right.  What would you prefer?

**Comment by jd284** [comment]
This has basically the same function as the Tundra ASM Ore->Water converter. (Except that it also needs the ISRU to produce fuel from ore first.)
So if this is meant to be balanced for MKS, the output should be much lower than that of the ASM, since it's so much lighter. Especially if the water is meant to just be a by-product of the electricity generation.

**Comment by boiler1** [comment]
I changed the efficiency to 25%. My intent is several fold.  First, the space shuttle had fuel cells that converted hydrogen and oxygen into electricity and water.  So this is the direct result.  I also watched "The Martian" where he burned fuel to create water as a buy product.  I don't think the efficiency should be high unless it is a hydrogen and oxygen fuel cell where it would have a relatively high efficiency.  As this is just an abstraction for a game it doesn't need to be and is more about balance.

As for balance, I think we lean on the inefficient side.  As people start to use it, and complain it is not right, it will be less troubling to raise efficiency than to lower it.

**Comment by BobPalmer** [comment]
(Will review this for an upcoming patch)

**Pull request merged**
