### PR TITLE
COrrected kontainers prices

### PR DESCRIPTION
**Pull request by zajc3w**
Hydrates, gypsum and dirt tank Cost were way too high  in kontainer_01(04).cfg files
Hopefully this time i did it against correct branch ;)

### CODE REVIEW

**Comment by zajc3w** [comment]
seems i did something wrong... again :(
it's so messed up for noob like me
is there an easy way to edit 4 in 1 pull request?

**Comment by fat-lobyte** [comment]
Yes, you can edit 4 files and commit them, then make a single pull request from that branch. Or you commit the files separately, but still make a single  pull request.

Here's the super-quick git-guide:

- A change is an added line or a deleted line
- A commit is made up from changes
- A branch is a chained series of commits
- A branch can be "merged" into another branch
- A pull request is a request that the repository owner merges your branch into their branch
- Multiple alternative branches and repositories exist, so you always have to specify which branch of which repo to merge into which branch of which repo.

ps.: If I'm not mistaken, the Kontainer stuff goes here: https://github.com/BobPalmer/Kolonization/tree/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/Kontainers

But leave it at this place for now, RoverDude will know what to do.

**Comment by zajc3w** [comment]
Thanks.
For some reason each edited file landed in separate patch, and i wasn't able to create single pull request for all 4 changes. So i created pull request against my own fork, merged and created one PR. If that's how it should be done then fine, a lot of clicking around for 4 files edit. Will have to create dummy repo and play with it a bit(a lot) :)

I know for sure that all changes should go to DEVELOP branch, at lest with RoverDude's mods but which repository is a good question here, probably both Kolonization and MKS.

**Comment by fat-lobyte** [comment]
Command line Git is better in this cases, but I guess that's a steep learning curve, especially if you don't do software development otherwise.

I think it might be just Kolonization, but I'm sure it's definitely not both, because "both" creats merge conflicts ;)

**Pull request merged**
