### PR TITLE
TAC-LS and CrossFeed Enabler configs

### PR DESCRIPTION
**Pull request by DenisDanilov**
Yes, I've gotten around to this too.

If you want the new configs to look pretty, you may need to add a few textures.

I added the Food container because there ARE already non-MKS solutions for air and water recycling (namely, electrolysis and Sabatier reaction).

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
Crossfeed Enabler is retired - NathanKell added that function to stock.

**Comment by DenisDanilov** [comment]
Finalized the conversion by replacing all of the additional containers and life support storage Supplies and Mulch. Merry Christmas!

**Comment by BobPalmer** [comment]
Closing this as it's against the master branch - all pull requests need to come through Develop please

**Comment by DenisDanilov** [comment]
Ack-ack. No problem, especially since I'm sporting the old bugged config.

**Pull request closed without merging**
